### PR TITLE
fix: default to files:read scope for Figma provider

### LINKED ISSUE #1827: Auth provider Figma uses deprecated scope
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Figma API [deprecated](https://www.figma.com/developers/api#authentication-scopes) the scope `file_read` and replaced it with more granual controls over the permissions requested from user. The auth code still uses the outdated scope that requests all the available permissions during sign in:

https://github.com/supabase/auth/blob/a7129df4e1d91a042b56ff1f041b9c6598825475/internal/api/provider/figma.go#L40-L43

## To Reproduce
Setting up sign in with Figma and one of the currently supported scopes results in broken authentication showing `Cannot pass in both the file_read and files:read scopes` during redirect.

```js
const { error } = await supabase.auth.signInWithOAuth({
    provider: 'figma',
    options: {
      redirectTo: authRedirect,
      scopes: 'files:read',
    },
  });
```

## Expected behavior

Figma API doesn't seem to provide a more minimalistic scope than `files:read` so I guess that should be the new default.

### PR DESCRIPTION
**Pull request by smogg**
Closes #1827 by defaulting to `files:read` oAuth scope for Figma as per the issue.

### CODE REVIEW

File: internal/api/provider/figma.go [hunk 1]
```diff
@@ -39,7 +39,7 @@ func NewFigmaProvider(ext conf.OAuthProviderConfiguration, scopes string) (OAuth
 
 	// Figma only provides the "file_read" scope.
```
Comment (bnjmnt4n) [inline internal/api/provider/figma.go:40]: This comment can probably also be deleted.

**Review by J0 — APPROVED** [review]
Thanks 🙏

**Comment by J0** [comment]
At first glance,  Figma docs don't need updating (couldn't find scope via ctrl-F)
