### PR TITLE
fix: expose `X-Supabase-Api-Version` header in CORS

### LINKED ISSUE #1589: Supabase should be sending X-Supabase-API-Version in Access-Control-Allow-Headers HTTP header
Hello everyone,

This is probably minor issue, but in cross-origin setups, the default configuration of `supabase/auth` does not work properly with relatively new versions on `supabase/auth-js`. #1377 introduced handling of `X-Supabase-Api-Version` header as a mechanism to choose corresponding API version, and in `auth-js` the client-side of this was implemented in https://github.com/supabase/auth-js/pull/855. 

Notice however, that this new header is not present in default CORS config in `auth`, as defined in [internal/api/api.go line 289](https://github.com/supabase/auth/blob/master/internal/api/api.go#L289) thus not present in `Access-Control-Allow-Headers` header that `supabase/auth` sends. This breaks existing cross-origin setups if you update to versions past PRs mentioned.

There is simple fix of adding `GOTRUE_CORS_ALLOWED_HEADERS=X-Supabase-Api-Version` to environment variables, it is however not documented. 

Therefore I'd suggest either adding `"X-Supabase-Api-Version"` (or `APIVersionHeaderName`) to default allowed headers for CORS, or add `GOTRUE_CORS_ALLOWED_HEADERS` env variable information to README (or both).

Thank you for all the great software,
BR,
ympek

### PR DESCRIPTION
**Pull request by hf**
Fixes #1589.

### CODE REVIEW

File: internal/api/api.go [hunk 1]
```diff
@@ -286,8 +286,8 @@ func NewAPIWithVersion(globalConfig *conf.GlobalConfiguration, db *storage.Conne
 
 	corsHandler := cors.New(cors.Options{
 		AllowedMethods:   []string{http.MethodGet, http.MethodPost, http.MethodPut, http.MethodDelete},
-		AllowedHeaders:   globalConfig.CORS.AllAllowedHeaders([]string{"Accept", "Authorization", "Content-Type", "X-Client-IP", "X-Client-Info", audHeaderName, useCookieHeader}),
-		ExposedHeaders:   []string{"X-Total-Count", "Link"},
+		AllowedHeaders:   globalConfig.CORS.AllAllowedHeaders([]string{"Accept", "Authorization", "Content-Type", "X-Client-IP", "X-Client-Info", audHeaderName, useCookieHeader, "X-Supabase-Api-Version"}),
```
Comment (ympek) [inline internal/api/api.go:289]: Might be better to use constant `APIVersionHeaderName` defined in the same package [internal/api/apiversions.go#L7](https://github.com/supabase/auth/blob/master/internal/api/apiversions.go#L7) instead of string literal

**Review by kangmingtay — APPROVED** [review]
