### PR TITLE
fix: add error codes to password login flow

### LINKED ISSUE #1631: "Invalid Login Credientals" AuthApiError should have an error code
# Bug report

- [O] I confirm this is a bug with Supabase, not with my own application. 
- [O] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Docs explicitly state:

> Errors originating from the server API classed as AuthApiError **always have a code property that can be used to identify the error returned by the server**. The status property is also present, encoding the HTTP status code received in the response.

Docs also suggest:

> Do not use string matching on error messages! Always use the name and code properties of error objects to identify the situation.

## To Reproduce

Hit `auth/v1/token?grant_type=password` with an incorrect email/password combination and `-H 'x-supabase-api-version: 2024-01-01'`, the result is

`{"error":"invalid_grant","error_description":"Invalid login credentials"}`

And in supabase-js the resulting AuthApiError object is

`{"__isAuthError":true,"name":"AuthApiError","status":400,"code":undefined}`

## Expected behavior

As the docs suggest, the code should be defined.

### PR DESCRIPTION
**Pull request by kangmingtay**
## What kind of change does this PR introduce?
* Add error codes to the password login flow, which fixes #1631 

## What is the current behavior?
* Most errors in the password login flow are returned as `oauthError`, which doesn't have support for an error code as the struct conforms to the [oauth error response](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2) specified in the RFC

## What is the new behavior?
* Errors which were previously returned as an `oauthError` struct now return `badRequestError` instead with the following error code `invalid_login_credentials`
* In certain cases, we can return existing error codes like `ErrorCodeUserBanned`, `ErrorCodeEmailNotConfirmed`, `ErrorCodePhoneNotConfirmed` or `ErrorCodeValidationFailed`
* Some error messages are updated to provide more clarity on the underlying error

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

File: internal/api/errorcodes.go [hunk 1]
```diff
@@ -82,4 +82,6 @@ const (
 	ErrorCodeMFATOTPEnrollDisabled             ErrorCode = "mfa_totp_enroll_not_enabled"
 	ErrorCodeMFATOTPVerifyDisabled             ErrorCode = "mfa_totp_verify_not_enabled"
 	ErrorCodeVerifiedFactorExists              ErrorCode = "mfa_verified_factor_exists"
+	//#nosec G101 -- Not a secret value.
+	ErrorCodeInvalidLoginCredentials ErrorCode = "invalid_login_credentials"
```
Comment (hf) [inline internal/api/errorcodes.go:86]: Could we do something without `login`? Like: `invalid_credentials`?

**Review by hf — APPROVED** [review]

File: internal/api/token.go [hunk 2]
```diff
@@ -199,17 +199,17 @@ func (a *API) ResourceOwnerPasswordGrant(ctx context.Context, w http.ResponseWri
 					return err
 				}
 			}
-			return oauthError("invalid_grant", InvalidLoginMessage)
+			return badRequestError(ErrorCodeInvalidLoginCredentials, InvalidLoginMessage)
 		}
 	}
 	if !isValidPassword {
-		return oauthError("invalid_grant", InvalidLoginMessage)
+		return badRequestError(ErrorCodeInvalidLoginCredentials, InvalidLoginMessage)
```
Comment (J0) [inline internal/api/token.go:206]: Not too sure how to decide between `badRequest` Error and unprocessable entity here.

File: internal/api/token.go [hunk 3]
```diff
@@ -199,17 +199,17 @@ func (a *API) ResourceOwnerPasswordGrant(ctx context.Context, w http.ResponseWri
...
 	}
 
 	if params.Email != "" && !user.IsConfirmed() {
-		return oauthError("invalid_grant", "Email not confirmed")
+		return badRequestError(ErrorCodeInvalidLoginCredentials, "Email not confirmed")
```
Comment (J0) [inline internal/api/token.go:210]: Likewise for the phone and email case here

File: internal/api/token.go (hunk 2 above)
Comment (kangmingtay) [reply internal/api/token.go:206]: badRequest for backward compatibility because that's what oauthError uses - i prefer unprocessible entity too

**Review by J0 — APPROVED** [review]
Looks good! Consider seeking an opinion from @hf on the status codes - personally not too sure

File: internal/api/token.go (hunk 2 above)
Comment (J0) [reply internal/api/token.go:206]: makes sense -let's keep it then

**Comment by tom-at-pixel** [comment]
Awesome! Thanks for doing this! Should these docs be updated? https://supabase.com/docs/reference/javascript/auth-error-codes

**Comment by tiltmaster** [comment]
is this fix live on stable version?

**Comment by devangpadhiyar** [comment]
This is still happening on supabase local dev environment
